In [1]:
import numpy as np

games = [
    "Phasmophobia",
    "Pacify",
    "Escape the backrooms",
    "Monument Valley",
    "Portal 2",
    "Resident Evil"
]

num_games = len(games)
num_users = 4
num_features = 3

Y = np.array([
    [5, 4, 0, 0],
    [4, 5, 0, 0],
    [4, 4, 0, 5],
    [0, 0, 5, 4],
    [0, 0, 4, 5],
    [5, 0, 0, 0]
])

R = (Y > 0).astype(int)

print(Y)
print(R)

[[5 4 0 0]
 [4 5 0 0]
 [4 4 0 5]
 [0 0 5 4]
 [0 0 4 5]
 [5 0 0 0]]
[[1 1 0 0]
 [1 1 0 0]
 [1 1 0 1]
 [0 0 1 1]
 [0 0 1 1]
 [1 0 0 0]]


In [16]:
np.random.seed(42)

X = np.random.randn(num_games, num_features)
W = np.random.randn(num_users, num_features)
b = np.random.randn(1, num_users)

print(f"X shape: {X.shape}")
print(f"W shape: {W.shape}")
print(f"b shape: {b.shape}")

X shape: (6, 3)
W shape: (4, 3)
b shape: (1, 4)


In [17]:
def cofi_cost_and_gradients(X, W, b, Y, R, lambda_):

    predictions = np.dot(X, W.T) + b

    error = (predictions - Y) * R

    cost = 0.5 * np.sum(error ** 2) + (lambda_ / 2) * (np.sum(X ** 2) + np.sum(W ** 2))

    X_grad = np.dot(error, W) + lambda_ * X
    W_grad = np.dot(error.T, X) + lambda_ * W
    b_grad = np.sum(error, axis = 0, keepdims = True)

    return cost, X_grad, W_grad, b_grad

In [18]:
itr = 1000
alpha = 0.01
lambda_ = 0.0

for i in range(itr):
    cost, X_grad, W_grad, b_grad = cofi_cost_and_gradients(X, W, b, Y, R, lambda_)

    X = X - alpha * X_grad
    W = W - alpha * W_grad
    b = b - alpha * b_grad

    if i % 200 == 0:
        print(f"Iteration {i:4d}: Cost {cost:.4f}")



Iteration    0: Cost 127.7145
Iteration  200: Cost 0.0024
Iteration  400: Cost 0.0000
Iteration  600: Cost 0.0000
Iteration  800: Cost 0.0000


In [22]:
predictions = np.dot(X, W.T) + b

user_id = 2
user_predictions = predictions[:, user_id]

for i in range(num_games):
    if R[i, user_id] == 0:
        print(f"Game: {games[i]:<22} | Predicted Rating: {user_predictions[i]:.2f} / 5.0")

Game: Phasmophobia           | Predicted Rating: 0.19 / 5.0
Game: Pacify                 | Predicted Rating: 1.65 / 5.0
Game: Escape the backrooms   | Predicted Rating: 0.26 / 5.0
Game: Resident Evil          | Predicted Rating: -0.41 / 5.0
